#include <iostream>
#include <string>

#include "st_ydl.hpp"

// file is generated by CMake
#include <st_ydl_version.h>

using namespace std;

int main(int argc, const char **argv)
{
    try
    {
        if (argc < 2 || argc > 3)
        {
            throw "Wrong number of arguments";
        }

        if (argc == 3 && ((stoi(argv[2]) < 0) || (stoi(argv[2]) > 9)))
        {
            throw "Wrong number of threads, mus be between 1 and 9.";
        }

        if (string(argv[1]) == "-?" || string(argv[1]) == "-h" || string(argv[1]) == "--help")
        {
            throw "";
        }
    }
    catch(const string &s)
    {
        cerr << "Error:\nt" << s << endl <<"\tPlease enter one file name (+ threads[1 - 8]), " << endl
             << "\tor display the version number with '-v' '--version'" << endl;
        exit(EXIT_FAILURE);
    }
    catch(...)
    {
        cerr << "INFO:" << endl <<"\tPlease enter one file name (+ threads[1 - 8]), " << endl
             << "\tor display the version number with '-v' '--version'" << endl;
        exit(EXIT_SUCCESS);
    }

    if (string(argv[1]) == "-v" || string(argv[1]) == "--version")
    {
        cout << "VERSION: " << ST_YDL_VERSION << endl;
        exit(EXIT_SUCCESS);
    }

    // start actual program 
    try
    {
        int number_of_threads = 2;
        if (argc == 3)
        {
            number_of_threads = stoi(argv[2]);
        }
        
        STydl *yt_vid = new STydl(argv[1]);

        yt_vid->download_multithreading(number_of_threads);

        cout << "\n -->Finished downloading!<--\n" << endl;

        delete yt_vid; 
    }
    catch(const exception &exc)
    {
        cerr << "ERROR (exception): " << exc.what() << endl;
        exit(EXIT_FAILURE);
    }
    catch (...)
    {
        cerr << "ERROR (unknown): Was catched at the end of the program...";
        exit(EXIT_FAILURE);
    }
    
    return 0;
}